insert into taxa (tx_euring,tx_sea_flag,tx_abv_de,tx_abv_dk,tx_name_lat,tx_name_de,tx_name_en,tx_name_dk) values
('06549',false,'av','alcsp','Alcidae indet.','Alkenvogel unbestimmt','Auklet sp.','uidenficeret alkefugl'),
('05120',false,'ap','caalp','Calidris alpina','Alpenstrandläufer','Dunlin','Almindelig Ryle'),
('05121',false,'apa','caala','Calidris alpina alpina','Alpenstrandläufer (Unterart alpina)','Dunlin (alpina)','Almindelig Ryle (alpina)'),
('11870',false,'a','tumer','Turdus merula','Amsel','Blackbird','Solsort'),
('04500',false,'af','haost','Haematopus ostralegus','Austernfischer','Oystercatcher','Strandskade'),
('10200',false,'ba','moalb','Motacilla alba','Bachstelze','White Wagtail','Hvid Vipstjert'),
('13640',false,'bam','pabia','Panurus biarmicus','Bartmeise','Bearded Tit','Skægmejse'),
('00710',false,'bt','subas','Sula bassana','Basstölpel','Northern Gannet','Sule'),
('03100',false,'bf','fasub','Falco subbuteo','Baumfalke','Hobby','Lærkefalk'),
('10090',false,'bp','antri','Anthus trivialis','Baumpieper','Tree Pipit','Skovpiber'),
('05190',false,'bek','gagal','Gallinago gallinago','Bekassine','Snipe','Dobbeltbekkasin'),
('02040',false,'bge','aymar','Aythya marila','Bergente','Greater Scaup','Bjergand'),
('16380',false,'ber','frmon','Fringilla montifringilla','Bergfink','Brambling','Kvækerfinke'),
('16620',false,'bhf','cafla','Carduelis flavirostris','Berghänfling','Twite','Bjergirisk'),
('13070',false,'bls','phbon','Phylloscopus bonelli','Berglaubsänger','Bonelli’s Warbler','Bjergløvsanger'),
('14900',false,'bem','repen','Remiz pendulinus','Beutelmeise','Penduline Tit','Pungmejse'),
('08400',false,'bie','meapi','Merops apiaster','Bienenfresser','Bee-eater','Biæder'),
('16650',false,'bks','loleu','Loxia leucoptera','Bindenkreuzschnabel','Two-barred Crossbill','Hvidvinget Korsnæb'),
('16630',false,'bir','carfl','Carduelis flammea','Birkenzeisig','Common Redpoll','Gråsisken'),
('01590',false,'bg','analb','Anser albifrons','Blässgans','Greater White-fronted Goose','Blisgås'),
('04290',false,'bh','fuatr','Fulica atra','Blässhuhn','Common Coot','Blishøne'),
('11060',false,'blk','lusve','Luscinia svecica','Blaukehlchen','Bluethroat','Blåhals'),
('14620',false,'bm','pacae','Parus caeruleus','Blaumeise','Blue Tit','Blåmejse'),
('16600',false,'hf','carca','Carduelis cannabina','Bluthänfling','Linnet','Tornirisk'),
('05810',false,'bom','laphi','Larus philadelphia','Bonapartemöwe','Bonaparte''s Gull','Bonapartemåge'),
('10050',false,'br','ancam','Anthus campestris','Brachpieper','Tawny Pipit','Markpiber'),
('01730',false,'be','tatad','Tadorna tadorna','Brandgans','Shelduck','Gravand'),
('06110',true,'bs','stsan','Sterna sandvicensis','Brandseeschwalbe','Sandwich Tern','Splitterne'),
('11370',false,'bk','sarub','Saxicola rubetra','Braunkehlchen','Whinchat','Bynkefugl'),
('05540',false,'bru','trgla','Tringa glareola','Bruchwasserläufer','Wood Sandpiper','Tinksmed'),
('16360',true,'b','frcoe','Fringilla coelebs','Buchfink','Chaffinch','Bogfinke'),
('08760',false,'bsp','demaj','Picoides major','Buntspecht','Great Spotted Woodpecker','Stor Flagspætte'),
('02919',false,'bu','buspe','Buteo indet.','Bussard unbestimmt','Buzzard sp.','våge sp.'),
('06350',false,'dl','urlom','Uria lomvia','Dickschnabellumme','Brünnich’s Guillemot','Polarlomvie'),
('15600',false,'do','comon','Corvus monedula','Dohle','Eurasian Jackdaw','Allike'),
('05200',false,'ds','gamed','Gallinago media','Doppelschnepfe','Great Snipe','Tredækker'),
('12750',false,'dg','sycom','Sylvia communis','Dorngrasmücke','Whitethroat','Tornsanger'),
('06020',false,'dm','ritri','Rissa tridactyla','Dreizehenmöwe','Kittiwake','Ride'),
('08980',false,'dzs','detri','Picoides tridactylus','Dreizehenspecht','Three-toed Woodpecker','tretået Spætte'),
('12069',false,'drs','turdus','Turdidae indet.','Drossel unbestimmt','Thrush sp.','uidentificeret Drossel'),
('12530',false,'dr','acaru','Acrocephalus arundinaceus','Drosselrohrsänger','Great Reed Warbler','Drosselrørsanger'),
('00430',false,'dstu','pugri','Puffinus griseus','Dunkler Sturmtaucher','Sooty Shearwater','Sodfarvet Skråpe'),
('05450',false,'dw','trery','Tringa erythropus','Dunkler Wasserläufer','Spotted Redshank','Sortklire'),
('15390',false,'ei','gagla','Garrulus garrulus','Eichelhäher','Eurasien Jay','Skovskade'),
('02060',true,'ee','somol','Somateria mollissima','Eiderente','Common Eider','Ederfugl'),
('02120',true,'eie','clhye','Clangula hyemalis','Eisente','Long-tailed Duck','Havlit'),
('05990',false,'em','lahyp','Larus hyperboreus','Eismöwe','Glaucous Gull','Gråmåge'),
('00220',true,'es','fugla','Fulmarus glacialis','Eissturmvogel','Northern Fulmar','Mallemuk'),
('00040',false,'et','gaimm','Gavia immer','Eistaucher','Great Northern Diver','Islom'),
('08310',false,'ev','alatt','Alcedo atthis','Eisvogel','Kingfisher','Isfugl'),
('15490',false,'e','pipic','Pica pica','Elster','Black-billed Magpie','Husskade'),
('02259',true,'en','anasp','Anatinae indet.','Ente unbestimmt','Duck sp.','uidenficeret And'),
('16540',false,'ez','caspi','Carduelis spinus','Erlenzeisig','Siskin','Grønsisken'),
('03219',false,'fku','falsp','Falco indet.','Falke unbestimmt','Falcon sp.','falk sp'),
('05680',false,'frm','stlon','Stercorarius longicaudus','Falkenraubmöwe','Long-tailed Skua','Lille Kjove'),
('03940',false,'fa','phaco','Phasianus colchicus','Fasan','Pheasant','Fasan'),
('09760',false,'fl','alarv','Alauda arvensis','Feldlerche','Skylark','Sanglærke'),
('12360',false,'fsl','lonae','Locustella naevia','Feldschwirl','Grasshopper Warbler','Græshoppesanger'),
('15980',false,'fe','pamon','Passer montanus','Feldsperling','Tree Sparrow','Skovspurv'),
('16660',false,'fk','locur','Loxia curvirostra','Fichtenkreuzschnabel','Common Crossbill','Lille Korsnæb'),
('16389',false,'fi','unfin','Fringilla indet.','Fink unbestimmt','Chaffinch sp.','finke sp'),
('03010',false,'fd','pahal','Pandion haliaetus','Fischadler','Osprey','Fiskeørn'),
('13120',false,'f','phtro','Phylloscopus trochilus','Fitis','Willow Warbler','Løvsanger'),
('06169',true,'fks','sthip','Sterna hirundo / paradisaea','Fluss-/Küstenseeschwalbe','Common/Arctic Tern','Fjordterne / Havterne'),
('04690',false,'frp','chdub','Charadrius dubius','Flussregenpfeifer','Little Ringed Plover','Lille Præstekrave'),
('06150',false,'fs','sthir','Sterna hirundo','Flussseeschwalbe','Common Tern','Fjordterne'),
('05560',false,'fu','achyp','Actitis hypoleucos','Flussuferläufer','Common Sandpiper','Mudderklire'),
('01699',true,'gä','anspe','Anserini indet.','Gans unbestimmt','Goose sp.','uidenficeret Gås'),
('02230',true,'gän','memer','Mergus merganser','Gänsesäger','Goosander','Stor Skallesluger'),
('14870',false,'gb','cebra','Certhia brachydactyla','Gartenbaumläufer','Short-toed Treecreeper','Korttået træløber'),
('12760',false,'ggm','sybor','Sylvia borin','Gartengrasmücke','Garden Warbler','Havesanger'),
('11220',false,'gr','phoph','Phoenicurus phoenicurus','Gartenrotschwanz','Redstart','Rødstjert'),
('10190',false,'ge','mocin','Motacilla cinerea','Gebirgsstelze','Grey Wagtail','Bjergvipstjert'),
('13000',false,'gbl','phino','Phylloscopus inornatus','Gelbbrauen-Laubsänger','Yellow-browed Warbler','Hvidbrynet Løvsanger'),
('00050',false,'gse','gaadm','Gavia adamsii','Gelbschnabel-Eistaucher','White-billed Diver','Hvidnæbbet lom'),
('00360',false,'ges','cadio','Calonectris diomedea','Gelbschnabel-Sturmtaucher','Cory’s Shearwater','Kuhls Skråpe'),
('12590',false,'gp','hiict','Hippolais icterina','Gelbspötter','Icterine Warbler','Gulbug'),
('03180',false,'ger','farus','Falco rusticolus','Gerfalke','Gyrfalcon','Jagtfalk'),
('17100',false,'d','pypyr','Pyrrhula pyrrhula','Gimpel','Bullfinch','Dompap'),
('16400',false,'gi','seser','Serinus serinus','Girlitz','European Serin','Gulirisk'),
('04869',false,'gokir','plaps','Pluvialis apricaria / squatarola','Gold-/Kiebitzregenpfeifer','Golden/Grey Plover','Hjejle / Strandhjejle'),
('18570',false,'g','emcit','Emberiza citrinella','Goldammer','Yellowhammer','Gulspurv'),
('13169',false,'gos','respe','Regulus indet.','Goldhähnchen unbestimmt','Kinglet sp.','Fuglekonge sp.'),
('12980',false,'ghl','phpro','Phylloscopus proregulus','Goldhähnchen-Laubsänger','Pallas‘s Warbler','Fuglekongesanger'),
('04850',false,'go','plapr','Pluvialis apricaria','Goldregenpfeifer','Golden Plover','Hjejle'),
('18820',false,'ga','emcal','Miliaria calandra','Grauammer','Corn Bunting','Bomlærke'),
('05070',false,'gbs','camel','Calidris melanotos','Graubrust-Strandläufer','Pectoral Sandpiper','Stribet ryle'),
('01610',true,'gg','anans','Anser anser','Graugans','Greylag Goose','Grågås'),
('01220',false,'fr','arcin','Ardea cinerea','Graureiher','Common Heron','Fiskehejre'),
('13350',false,'grs','mustr','Muscicapa striata','Grauschnäpper','Spotted Flycatcher','Grå Fluesnapper'),
('08550',false,'gra','pican','Picus canus','Grauspecht','Grey-headed Woodpecker','Gråspætte'),
('02748',true,'gv','rovsp','Accipitridae indet.','Greifvogel unbestimmt','Bird of prey sp.','uidenficeret rovfugl'),
('00950',false,'rod','boste','Botaurus stellaris','Große Rohrdommel','Eurasian Bittern','Rørdrum'),
('05410',false,'gbr','nuarq','Numenius arquata','Großer Brachvogel','Curlew','Stor Regnspove'),
('06005',true,'gm','larus','Larus spec.','Großmöwe unbestimmt','Large gull sp.','uidenficeret stormåge'),
('16490',false,'gf','cachl','Carduelis chloris','Grünfink','Greenfinch','Grønirisk'),
('12930',false,'grl','phytr','Phylloscopus trochiloides','Grünlaubsänger','Greenish Warbler','Lundsanger'),
('05480',false,'gs','trneb','Tringa nebularia','Grünschenkel','Greenshank','Hvidklire'),
('08560',false,'gsp','pivir','Picus viridis','Grünspecht','Green Woodpecker','Grønspætte'),
('06380',false,'gry','cegry','Cepphus grylle','Gryllteiste','Black Guillemot','Tejst'),
('02670',false,'ha','acgen','Accipiter gentilis','Habicht','Northern Goshawk','Duehøg'),
('13480',false,'hb','fialb','Ficedula albicollis','Halsbandschnäpper','Collared Flycatcher','Hvidhalset Fluesnapper'),
('09720',false,'hl','gacri','Galerida cristata','Haubenlerche','Crested Lark','Toplærke'),
('14540',false,'ham','pacri','Parus cristatus','Haubenmeise','Crested Tit','Topmejse'),
('00090',true,'hat','pocri','Podiceps cristatus','Haubentaucher','Great Crested Grebe','Toppet Lappedykker'),
('11210',false,'hr','phoch','Phoenicurus ochruros','Hausrotschwanz','Black Redstart','Husrødstjert'),
('15910',false,'h','padom','Passer domesticus','Haussperling','House Sparrow','Gråspurv'),
('06655',false,'hx','co''do','Columba livia domestica','Haustaube','Feral Pigeon','Tamdue'),
('10840',false,'he','prmod','Prunella modularis','Heckenbraunelle','Dunnock','Jernspurv'),
('09740',false,'hei','luarb','Lullula arborea','Heidelerche','Woodlark','Hedelærke'),
('06008',true,'hmm','lafum','Larus fuscus / marinus','Herings-/Mantelmöwe','Great/Lesser Black-backed Gull','Sildemåge / Svartbag '),
('05919',false,'hsm','lafug','Larus argentatus / fuscus','Herings-/Silbermöwe','Herring/Lesser Black-backed Gull','Silde-/Sølvmåge'),
('05910',true,'hm','lafus','Larus fuscus','Heringsmöwe','Lesser Black-backed Gull','Sildemåge'),
('01520',false,'hö','cyolo','Cygnus olor','Höckerschwan','Mute Swan','Knopsvane'),
('06680',false,'hot','cooen','Columba oenas','Hohltaube','Stock Dove','Huldue'),
('05170',false,'ka','phpug','Philomachus pugnax','Kampfläufer','Ruff','Brushane'),
('01660',false,'kag','brcan','Branta canadensis','Kanadagans','Canada Goose','Kanadagås'),
('16790',false,'kar','caery','Carpodacus erythrinus','Karmingimpel','Common Rosefinch','Karmindompap'),
('17170',false,'kb','cococ','Coccothraustes coccothraustes','Kernbeißer','Hawfinch','Kærnebider'),
('04930',false,'ki','vavan','Vanellus vanellus','Kiebitz','Lapwing','Vibe'),
('04860',false,'kir','plsqu','Pluvialis squatarola','Kiebitzregenpfeifer','Grey Plover','Strandhjejle'),
('16680',false,'kks','lopyt','Loxia pytyopsittacus','Kiefernkreuzschnabel','Parrot Crossbill','Stor Korsnæb'),
('12740',false,'kgm','sycur','Sylvia curruca','Klappergrasmücke','Lesser Whitethroat','Gærdesanger'),
('14790',false,'kl','sieur','Sitta europaea','Kleiber','Nuthatch','Spætmejse'),
('04100',false,'ksh','popar','Porzana parva','Kleines Sumpfhuhn','Little Crake','Lille Rørvagtel'),
('05909',true,'km','laris','Larus / Rissa indet.','Kleinmöwe unbestimmt','Lesser gull sp.','uidenficeret småmåge'),
('08870',false,'ksp','demin','Picoides minor','Kleinspecht','Lesser Spotted Woodpecker','Lille Flagspætte'),
('01910',false,'kne','anque','Anas querquedula','Knäkente','Garganey','Atlingand'),
('04960',false,'knt','cacan','Calidris canutus','Knutt','Knot','Islandsk Ryle'),
('14640',false,'ko','pamaj','Parus major','Kohlmeise','Great Tit','Musvit'),
('01960',false,'koe','neruf','Netta rufina','Kolbenente','Red-crested Pochard','Rødhovedet and'),
('15720',false,'kra','corco','Corvus corax','Kolkrabe','Common Raven','Ravn'),
('00720',true,'k','phcar','Phalacrocorax carbo','Kormoran','Great Cormorant','Skarv'),
('02610',true,'kw','cicya','Circus cyaneus','Kornweihe','Hen Harrier','Blå Kærhøg'),
('06470',false,'krt','alall','Alle alle','Krabbentaucher','Little Auk','Søkonge'),
('15749',true,'krä','cospe','Corvus indet.','Krähe unbestimmt','Crow sp.','uidenficeret Kragefugl'),
('00800',false,'krs','phari','Phalacrocorax aristotelis','Krähenscharbe','Shag Cormorant','Topskarv'),
('04330',false,'kch','grgru','Grus grus','Kranich','Common Crane','Trane'),
('01840',false,'kre','ancre','Anas crecca','Krickente','Green-winged Teal','Krikand'),
('07240',false,'ku','cucan','Cuculus canorus','Kuckuck','Cuckoo','Gøg'),
('01110',false,'kur','buibi','Bubulcus ibis','Kuhreiher','Cattle Egret','Kohejre'),
('01580',false,'kg','anbra','Anser brachyrhynchus','Kurzschnabelgans','Pink-footed Goose','Kortnæbbet Gås'),
('06160',true,'ks','stepa','Sterna paradisaea','Küstenseeschwalbe','Arctic Tern','Havterne'),
('05820',true,'lm','larid','Larus ridibundus','Lachmöwe','Black-headed Gull','Hættemåge'),
('06050',false,'las','genil','Gelochelidon nilotica','Lachseeschwalbe','Gull-billed Tern','Sandterne'),
('00129',true,'lt','pospe','Podicipedidae indet.','Lappentaucher unbestimmt','Grebe sp.','uidenficeret Lappedykker'),
('13129',false,'ls','physp','Phylloscopus indet.','Laubsänger unbestimmt','Leef Warbler sp.','uidenficeret Sanger'),
('01940',false,'le','ancly','Anas clypeata','Löffelente','Northern Shoveler','Skeand'),
('01440',false,'lf','plleu','Platalea leucorodia','Löffler','Common Spoonbill','Skestork'),
('06000',true,'mm','lamar','Larus marinus','Mantelmöwe','Great Black-backed Gull','Svartbag'),
('07950',false,'ms','apapu','Apus apus','Mauersegler','Swift','Mursejler'),
('02870',false,'mb','bubut','Buteo buteo','Mäusebussard','Eurasian Buzzard','Musvåge'),
('05100',false,'mst','camar','Calidris maritima','Meerstrandläufer','Purple Sandpiper','Sortgrå Ryle'),
('10010',false,'m','deurb','Delichon urbica','Mehlschwalbe','House Martin','Bysvale'),
('03090',true,'mer','facol','Falco columbarius','Merlin','Merlin','Dværgfalk'),
('02399',false,'mu','mispe','Milvus indet.','Milan unbestimmt','Kite sp.','Glente sp.'),
('12020',false,'mi','tuvis','Turdus viscivorus','Misteldrossel','Mistle Thrush','Misteldrossel'),
('05926',true,'wmm','lacam','Larus cachinnans michahellis','Mittelmeermöwe','Yellow-legged Gull (michahelis)','Middelhavssølvmåge'),
('00463',false,'mms','pupum','Puffinus puffinus mauretanicus','Mittelmeer-Sturmtaucher','Balearic Shearwater','Balearskråpe'),
('02210',false,'mis','meser','Mergus serrator','Mittelsäger','Red-breasted Merganser','Toppet Skallesluger'),
('08830',false,'msp','demed','Picoides medius','Mittelspecht','Middle Spotted Woodpecker','Mellemflagspætte'),
('12770',false,'mg','syatr','Sylvia atricapilla','Mönchsgrasmücke','Blackcap','Munk'),
('02020',false,'moe','aynyr','Aythya nyroca','Moorente','Ferrugineous Duck','Hvidøjet And'),
('04820',false,'mrp','chmor','Charadrius morinellus','Mornellregenpfeifer','Dotterel','Pomeransfugl'),
('06049',true,'mö','larsp','Laridae indet.','Möwe unbestimmt','Gull sp.','uidenficeret Måge'),
('11040',false,'n','lumeg','Luscinia megarhynchos','Nachtigall','Nightingale','Sydlig nattergal'),
('01040',false,'nr','nynyc','Nycticorax nycticorax','Nachtreiher','Black-crowned Night Heron','Nathejre'),
('15673',false,'ne','cocox','Corvus corone cornix','Nebelkrähe','Hooded Crow','Gråkrage'),
('15150',false,'nt','lacol','Lanius collurio','Neuntöter','Red-backed Shrike','Rødrygget Tornskade'),
('01700',false,'nig','alaeg','Alopochen aegyptiacus','Nilgans','Egyptian Goose','Nilgås'),
('01670',true,'ng','brleu','Branta leucopsis','Nonnengans','Barnacle Goose','Bramgås'),
('05640',false,'od','phlob','Phalaropus lobatus','Odinshühnchen','Red-necked Phalarope','Odinshane'),
('09780',false,'ol','eralp','Eremophila alpestris','Ohrenlerche','Shore Lark','Bjerglærke'),
('00110',false,'ot','poaur','Podiceps auritus','Ohrentaucher','Slavonian Grebe','Nordisk Lappedykker'),
('18660',false,'o','emhor','Emberiza hortulana','Ortolan','Ortolan Bunting','Hortulan'),
('06540',false,'pt','frarc','Fratercula arctica','Papageitaucher','Puffin','Lunde'),
('01790',false,'pe','anpen','Anas penelope','Pfeifente','Eurasian Wigeon','Pibeand'),
('05340',false,'ps','lilap','Limosa lapponica','Pfuhlschnepfe','Bar-tailed Godwit','Lille Kobbersneppe'),
('10159',false,'psp','antsp','Motacillidae indet.','Pieper unbestimmt','Pipit sp.','uidenficeret Piber'),
('15080',false,'p','orori','Oriolus oriolus','Pirol','Golden Oriole','Pirol'),
('16640',false,'pbz','cahor','Carduelis hornemanni','Polarbirkenzeisig','Arctic Redpoll','Hvidsisken'),
('05980',false,'pm','lagla','Larus glaucoides','Polarmöwe','Iceland Gull','Hvidvinget Måge'),
('02070',false,'pre','sospe','Somateria spectabilis','Prachteiderente','King Eider','Kongeederfugl'),
('00030',false,'ptt','gaarc','Gavia arctica','Prachttaucher','Black-throated Diver','Sortstrubet Lom'),
('01240',false,'pur','armel','Ardea purpurea','Purpurreiher','Purple Heron','Purpurhejre'),
('15671',false,'ra','cocoe','Corvus corone corone','Rabenkrähe','Carrion Crow','Sortkrage'),
('05709',false,'rm','skua','Stercorariidae indet.','Raubmöwe unbestimmt','Skua sp.','uidenficeret Kjove'),
('06060',true,'rbs','stcas','Sterna caspia','Raubseeschwalbe','Caspian Tern','Rovterne'),
('15200',false,'rw','laexc','Lanius excubitor','Raubwürger','Great Grey Shrike','Stor Tornskade'),
('09920',false,'r','hirus','Hirundo rustica','Rauchschwalbe','Swallow','Landsvale'),
('02900',false,'rb','bulag','Buteo lagopus','Rauhfußbussard','Rough-legged Buzzard','Fjeldvåge'),
('03670',false,'reb','peper','Perdix perdix','Rebhuhn','Grey Partridge','Agerhøne'),
('05380',false,'rbr','nupha','Numenius phaeopus','Regenbrachvogel','Whimbrel','Lille Regnspove'),
('04839',false,'ru','chspe','Charadrius indet.','Regenpfeifer unbestimmt','Plover sp.','Præstekrave sp'),
('02030',true,'re','ayful','Aythya fuligula','Reiherente','Tufted Duck','Troldand'),
('11860',false,'rdr','tutor','Turdus torquatus','Ringdrossel','Ring Ouzel','Ringdrossel'),
('01680',false,'rg','brber','Branta bernicla','Ringelgans','Brent Goose','Knortegås'),
('1683',false,'rgn','brben','Branta bernicla nigricans','Ringelgans (Unterart nigricans)','Black-bellied Brent Goose','Sortbuget Knortegås'),
('06700',false,'rt','copal','Columba palumbus','Ringeltaube','Woodpigeon','Ringdue'),
('18770',false,'ro','emsch','Emberiza schoeniclus','Rohrammer','Reed Bunting','Rørspurv'),
('12549',false,'rsp','acspe','Acrocephalus indet.','Rohrsänger unbestimmt','Reed-warblers','Acrosephalus sp'),
('12380',false,'ros','lolus','Locustella luscinioides','Rohrschwirl','Savi’s Warbler','Savisanger'),
('02600',false,'row','ciaer','Circus aeruginosus','Rohrweihe','Marsh Harrier','Rørhøg'),
('01710',false,'rog','tafer','Tadorna ferruginea','Rostgans','Ruddy Shelduck','Rustand'),
('12010',true,'rd','tuili','Turdus iliacus','Rotdrossel','Redwing','Vindrossel'),
('03070',false,'rff','faves','Falco vespertinus','Rotfußfalke','Red-footed Falcon','Aftenfalk'),
('01690',false,'rhg','brruf','Branta ruficollis','Rothalsgans','Red-breasted Goose','Rødhalset gås'),
('00100',false,'rht','pogri','Podiceps grisegena','Rothalstaucher','Red-necked Grebe','Gråstrubet Lappedykker'),
('10990',false,'rk','errub','Erithacus rubecula','Rotkehlchen','Robin','Rødhals'),
('10120',false,'rkp','ancer','Anthus cervinus','Rotkehlpieper','Red-throated Pipit','Rødstrubet Piber'),
('15230',false,'rkw','lasen','Lanius senator','Rotkopfwürger','Woodchat Shrike','Rødhovedet Tornskade'),
('02390',false,'rom','mimil','Milvus milvus','Rotmilan','Red Kite','Rød Glente'),
('05460',false,'rs','trtot','Tringa totanus','Rotschenkel','Redshank','Rødben'),
('11061',false,'blkr','lussv','Luscinia svecica svecica','Rotsterniges Blaukehlchen','Red-spotted Bluethroat','Nordlig Blåhals'),
('11050',false,'rbk','lucal','Luscinia calliope','Rubinkehlchen','Siberian Rubythroat','Rubinnattergal'),
('01570',false,'sg','anfab','Anser fabalis','Saatgans','Bean Goose','Sædgås'),
('15630',false,'sa','cofru','Corvus frugilegus','Saatkrähe','Rook','Råge'),
('04560',false,'sb','reavo','Recurvirostra avosetta','Säbelschnäbler','Avocet','Klyde'),
('02239',false,'sä','mersp','Mergus indet.','Säger unbestimmt','Merganser sp.','uidenficeret Skallesluger'),
('02150',true,'se','mefus','Melanitta fusca','Samtente','Velvet Scoter','Fløjlsand'),
('04970',false,'san','caalb','Calidris alba','Sanderling','Sanderling','Sandløber'),
('04700',false,'srp','chhia','Charadrius hiaticula','Sandregenpfeifer','Ringed Plover','Stor Præstekrave'),
('10170',false,'sz','mofla','Motacilla flava','Schafstelze','Yellow Wagtail','Gul Vipstjert'),
('02090',false,'sce','poste','Polysticta stelleri','Scheckente','Steller''s Eider','Stellersand'),
('02930',false,'sca','aqcla','Aquila clanga','Schelladler','Spotted Eagle','Stor Skrigeørn'),
('02180',false,'sle','bucla','Bucephala clangula','Schellente','Common Goldeneye','Hvinand'),
('12430',false,'sr','acsch','Acrocephalus schoenobaenus','Schilfrohrsänger','Sedge Warbler','Sivsanger'),
('12370',false,'ssc','loflu','Locustella fluviatilis','Schlagschwirl','River Warbler','Flodsanger'),
('02560',false,'sla','cigal','Circaetus gallicus','Schlangenadler','Short-toed Eagle','Slangeørn'),
('07350',false,'sel','tyalb','Tyto alba','Schleiereule','Barn Owl','Slørugle'),
('05699',false,'ssf','stlpm','Stercorarius longicaudus/parasiticus/pomarinus','Schmarotzer-/Spatel-/Falkenraubmöwe','Long-tailed/Arctic/Pomarine Skua','Lille Kjove/Almindelig Kjove/ Mellemkjove'),
('05698',false,'ssrm','stpap','Stercorarius parasiticus / pomarinus','Schmarotzer-/Spatelraubmöwe','Arctic/Pomarine Skua','Almindelig / Mellemkjove'),
('05670',false,'srm','stpar','Stercorarius parasiticus','Schmarotzerraubmöwe','Arctic Skua','Almindelig Kjove'),
('01820',false,'sne','anstr','Anas strepera','Schnatterente','Gadwall','Knarand'),
('18500',false,'sna','plniv','Plectrophenax nivalis','Schneeammer','Snow Bunting','Snespurv'),
('07490',false,'seu','nysca','Nyctea scandiaca','Schnee-Eule','Snowy Owl','Sneugle'),
('01630',false,'sng','ancae','Anser caerulescens','Schneegans','Snow Goose','Snegås'),
('02920',false,'sra','aqpom','Aquila pomarina','Schreiadler','Lesser Spotted Eagle','Lille skrigeørn'),
('10019',false,'scu','hirsp','Hirundinidae indet.','Schwalbe unbestimmt','Swallow sp.','Ubestemt svale'),
('05790',false,'scm','lasab','Larus sabini','Schwalbenmöwe','Sabine’s Gull','Sabinemåge'),
('01559',true,'sch','cyspe','Cygnidae indet.','Schwan unbestimmt','Swan sp.','uidenficeret Svane'),
('14370',false,'sme','aecau','Aegithalos caudatus','Schwanzmeise','Long-tailed Tit','Halemejse'),
('00140',false,'sba','dimel','Diomedea melanophris','Schwarzbrauenalbatros','Black-browed Mollymawk','Sortbrynet Albatros'),
('00120',false,'sht','ponig','Podiceps nigricollis','Schwarzhalstaucher','Black-necked Grebe','Sorthalset Lappedykker'),
('11390',false,'sk','sator','Saxicola torquata','Schwarzkehlchen','Stonechat','Sortstrubet Bynkefugl'),
('05750',false,'skm','lamel','Larus melanocephalus','Schwarzkopfmöwe','Mediterranean Gull','Sorthovedet Måge'),
('02250',false,'ske','oxjam','Oxyura jamaicensis','Schwarzkopf-Ruderente','Ruddy Duck','Amerikansk Skarveand'),
('02380',false,'swm','mimig','Milvus migrans','Schwarzmilan','Black Kite','Sort Glente'),
('00460',false,'sst','pupuf','Puffinus puffinus','Schwarzschnabel-Sturmtaucher','Manx Shearwater','Almindelig Skråpe'),
('08630',false,'ssp','drmar','Dryocopus martius','Schwarzspecht','Black Woodpecker','Sortspætte'),
('01310',false,'sso','cinig','Ciconia nigra','Schwarzstorch','Black Stork','Sort stork'),
('02430',false,'sea','haalb','Haliaeetus albicilla','Seeadler','White-tailed Eagle','Havørn'),
('04770',false,'ser','chale','Charadrius alexandrinus','Seeregenpfeifer','Kentish Plover','Hvidbrystet Præstekrave'),
('06299',true,'ss','stnsp','Sterninae indet.','Seeschwalbe unbestimmt','Tern sp.','uidenficeret Terne'),
('00059',true,'st','gavia','Gaviidae indet.','Seetaucher unbestimmt','Diver sp.','uidenficeret Lom'),
('12420',false,'seg','acrpa','Acrocephalus paludicola','Seggenrohrsänger','Aquatic Warbler','Vandsanger'),
('01190',false,'sed','eggar','Egretta garzetta','Seidenreiher','Little Egret','Silkehejre'),
('10480',false,'sei','bogar','Bombycilla garrulus','Seidenschwanz','Waxwing','Silkehale'),
('05090',false,'sis','cafer','Calidris ferruginea','Sichelstrandläufer','Curlew Sandpiper','Krumnæbbet Ryle'),
('05929',false,'ssm','lacaa','Larus argentatus / canus','Silber-/Sturmmöwe','Herring/Common Gull','Sølvmåge / Stormmåge'),
('05920',true,'sm','laarg','Larus argentatus','Silbermöwe','Herring Gull','Sølvmåge'),
('01210',true,'sir','egalb','Egretta alba','Silberreiher','Great White Egret','Sølvhejre'),
('12000',false,'si','tuphi','Turdus philomelos','Singdrossel','Song Thrush','Sangdrossel'),
('01540',false,'siw','cycyg','Cygnus cygnus','Singschwan','Whooper Swan','Sangsvane'),
('19999',false,'sv','unpas','Passeriformes indet.','Singvogel unbestimmt','Passerine sp.','uidenficeret spurvefugl'),
('05690',false,'sku','stsku','Stercorarius skua','Skua','Skua','Storkjove'),
('13150',false,'sgh','reign','Regulus ignicapillus','Sommergoldhähnchen','Firecrest','Rødtoppet Fuglekonge'),
('02170',false,'spt','buisl','Bucephala islandica','Spatelente','Barrow’s Goldeneye','Islandsk Hvinand'),
('05660',false,'spm','stpom','Stercorarius pomarinus','Spatelraubmöwe','Pomarine Skua','Mellemkjove'),
('02690',false,'sp','acnis','Accipiter nisus','Sperber','European Sparrow Hawk','Spurvehøg'),
('12730',false,'sgm','synis','Sylvia nisoria','Sperbergrasmücke','Barred Warbler','Høgesanger'),
('07510',false,'spk','glpas','Glaucidium passerinum','Sperlingskauz','Pygmy Owl','Spurveugle'),
('01890',false,'spe','anacu','Anas acuta','Spießente','Northern Pintail','Spidsand'),
('18470',false,'spa','calap','Calcarius lapponicus','Spornammer','Lapland Longspur','Laplandsværling'),
('10020',false,'spp','anric','Anthus richardi','Spornpieper','Richard’s Pipit','Storpiber'),
('11030',false,'spr','lulus','Luscinia luscinia','Sprosser','Thrush Nightingale','Noordse Nachtegaal'),
('15820',false,'s','stvul','Sturnus vulgaris','Star','Common Starling','Stær'),
('02960',false,'sta','aqchr','Aquila chrysaetos','Steinadler','Golden Eagle','Kongeørn'),
('07570',false,'stk','atnoc','Athene noctua','Steinkauz','Little Owl','Kirkeugle'),
('11460',false,'sts','oeoen','Oenanthe oenanthe','Steinschmätzer','Wheatear','Stenpikker'),
('05610',false,'sw','arint','Arenaria interpres','Steinwälzer','Turnstone','Stenvender'),
('04550',false,'stf','hihim','Himantopus himantopus','Stelzenläufer','Black-winged Stilt','Stylteløber'),
('05939',true,'wms','lacac','Larus cachinnans cachinnans','Steppenmöwe','Caspian Gull','Kaspisk Måge'),
('02620',false,'spw','cimac','Circus macrourus','Steppenweihe','Pallid Harrier','Steppehøg'),
('00020',true,'stt','gaste','Gavia stellata','Sterntaucher','Red-throated Diver','Rødstrubet Lom'),
('16530',false,'sti','cacar','Carduelis carduelis','Stieglitz','Goldfinch','Stillits'),
('01860',false,'ste','anpla','Anas platyrhynchos','Stockente','Mallard','Gråand'),
('05129',false,'stl','caspe','Calidris indet.','Strandläufer unbestimmt','Stint sp.','uidenficeret Ryle'),
('10143',false,'stp','anlit','Anthus spinoletta littoralis','Strandpieper (Unterart littoralis)','Scandinavian Rock Pipit','Skærpiber'),
('01620',false,'srg','anind','Anser indicus','Streifengans','Bar-headed Goose','Indisk gås'),
('05900',true,'stm','lacan','Larus canus','Sturmmöwe','Common Gull','Stormmåge'),
('00520',false,'stw','hypel','Hydrobates pelagicus','Sturmschwalbe','European Storm Petrel','Lille Stormsvale'),
('00499',false,'stu','puspe','Puffinus indet.','Sturmtaucher unbestimmt','Shearwater sp.','uidenficeret Skråpe'),
('05140',false,'sul','lifal','Limicola falcinellus','Sumpfläufer','Broad-billed Sandpiper','Kærløber'),
('14400',false,'sum','papal','Parus palustris','Sumpfmeise','Marsh Tit','Sumpmejse'),
('07680',false,'soe','asfla','Asio flammeus','Sumpfohreule','Short-eared Owl','Mosehornugle'),
('12500',false,'su','acpal','Acrocephalus palustris','Sumpfrohrsänger','Marsh Warbler','Kærsanger'),
('01980',false,'tfe','ayfer','Aythya ferina','Tafelente','Common Pochard','Taffeland'),
('15570',false,'tah','nucar','Nucifraga caryocatactes','Tannenhäher','Spotted Nutcracker','Nøddekrige'),
('14610',false,'tm','paate','Parus ater','Tannenmeise','Coal Tit','Sortmejse'),
('06999',false,'tb','colsp','Columbidae indet.','Taube unbestimmt','Dove sp.','uidenficeret Due'),
('04240',false,'th','gachl','Gallinula chloropus','Teichhuhn','Moorhen','Grønbenet Rørhøne'),
('12510',false,'t','acsci','Acrocephalus scirpaceus','Teichrohrsänger','Reed Warbler','Rørsanger'),
('05470',false,'twl','trsta','Tringa stagnatilis','Teichwasserläufer','Marsh Sandpiper','Damklire'),
('05020',false,'tem','catem','Calidris temminckii','Temminckstrandläufer','Temminck’s Stint','Temmincksryle'),
('05550',false,'tkl','xecin','Xenus cinereus','Terekwasserläufer','Terek Sandpiper','Terekklire'),
('5970',false,'tym','latha','Larus thayeri','Thayer-Möwe','Thayer´s Gull','Inuitmåge'),
('06360',true,'ta','altor','Alca torda','Tordalk','Razorbill','Alk'),
('02139',false,'tse','mespe','Melanitta indet.','Trauer-/Samtente','Black/Velvet Scoter','Sortand / Fløjlsand'),
('02130',true,'te','menig','Melanitta nigra','Trauerente','Common Scoter','Sortand'),
('13490',false,'trs','fihyp','Ficedula hypoleuca','Trauerschnäpper','Pied Flycatcher','Broget Fluesnapper'),
('06270',false,'ts','chnig','Chlidonias niger','Trauerseeschwalbe','Black Tern','Sortterne '),
('04590',false,'tri','buoed','Burhinus oedicnemus','Triel','Stone Curlew','Triel'),
('06340',true,'tl','uraal','Uria aalge','Trottellumme','Guillemot','Lomvie'),
('06345',true,'tt','alkur','Alca torda / Uria aalge','Trottellumme/Tordalk','Common Guillemot/Razorbill','Lomvie / Alk'),
('04080',false,'tsu','popor','Porzana porzana','Tüpfelsumpfhuhn','Spotted Crake','Plettet Rørvagtel'),
('06840',false,'tüt','stdec','Streptopelia decaocto','Türkentaube','Collared Dove','Tyrkerdue'),
('03040',true,'tf','fatin','Falco tinnunculus','Turmfalke','Eurasian Kestrel','Tårnfalk'),
('06870',false,'tut','sttur','Streptopelia turtur','Turteltaube','Turtle Dove','Turteldue'),
('05320',false,'us','lilim','Limosa limosa','Uferschnepfe','Black-tailed Godwit','Stor Kobbersneppe'),
('09810',false,'uf','ririp','Riparia riparia','Uferschwalbe','Sand Martin','Digesvale'),
('15430',false,'ugh','peinf','Perisoreus infaustus','Unglückshäher','Siberian Jay','Lavskrige'),
('11980',false,'wd','tupil','Turdus pilaris','Wacholderdrossel','Fieldfare','Sjagger'),
('03700',false,'wa','cocot','Coturnix coturnix','Wachtel','Quail','Vagtel'),
('04210',false,'wk','crcre','Crex crex','Wachtelkönig','Corncrake','Engsnarrer'),
('07689',false,'wsoe','asofl','Asio otus / flammeus','Wald-/Sumpfohreule','Long-eared/Short eared Owl','Skov- / Mosehornugle'),
('14860',false,'wb','cefam','Certhia familiaris','Waldbaumläufer','Treecreeper','Træløber'),
('07610',false,'wz','stalu','Strix aluco','Waldkauz','Tawny Owl','Natugle'),
('13080',false,'wls','phsib','Phylloscopus sibilatrix','Waldlaubsänger','Wood Warbler','Skovsanger'),
('07670',false,'woe','asotu','Asio otus','Waldohreule','Long-eared Owl','Skovhornugle'),
('10080',false,'wap','anhod','Anthus hodgsoni','Waldpieper','Olive-backed Pipit','Taigapiber'),
('05290',false,'ws','scrus','Scolopax rusticola','Waldschnepfe','Woodcock','Skovsneppe'),
('05530',false,'waw','troch','Tringa ochropus','Waldwasserläufer','Green Sandpiper','Svaleklire'),
('03200',false,'wf','faper','Falco peregrinus','Wanderfalke','Peregrine Falcon','Vandrefalk'),
('12950',false,'wal','phbor','Phylloscopus borealis','Wanderlaubsänger','Arctic Warbler','Nordsanger'),
('10500',false,'waa','cicin','Cinclus cinclus','Wasseramsel','Dipper','Vandstær'),
('04070',false,'wr','raaqu','Rallus aquaticus','Wasserralle','Water Rail','Vandrikse'),
('05659',false,'li','unwad','Limicolae indet.','Watvogel unbestimmt','Wader sp.','uidenficeret vadefugl'),
('14420',false,'wem','parmo','Parus montanus','Weidenmeise','Willow Tit','Fyrremejse'),
('02649',false,'wu','cispe','Circus indet.','Weihe unbestimmt','Harrier sp.','Kærhøg sp'),
('06280',false,'wfs','chleu','Chlidonias leucopterus','Weißflügel-Seeschwalbe','White-winged Tern','Hvidvinget Terne'),
('05927',false,'wm','','Larus cachinnans','Weißkopfmöwe','Yellow-legged Gull','cachinnans  Måge'),
('02260',false,'wke','oxleu','Oxyura leucocephala','Weißkopf-Ruderente','White-headed Duck','Hvidhovedet And'),
('08840',false,'wrs','deleu','Picoides leucotos','Weißrückenspecht','White-backed Woodpecker','Hvidrygget spætte'),
('11062',false,'blkw','lusvc','Luscinia svecica cyanecula','Weißsterniges Blaukehlchen','White-spotted Bluethroat','Blåhals (cyanecula)'),
('01340',false,'wst','cicic','Ciconia ciconia','Weißstorch','White Stork','Hvid Stork'),
('00550',false,'wl','ocleu','Oceanodroma leucorhoa','Wellenläufer','Leach’s Storm-Petrel','Stor Stormsvale'),
('08480',false,'wh','jytor','Jynx torquilla','Wendehals','Wryneck','Vendehals'),
('02310',false,'wsb','peapi','Pernis apivorus','Wespenbussard','Honey-Buzzard','Hvepsevåge'),
('08460',false,'wi','uoepo','Upupa epops','Wiedehopf','Hoopoe','Hærfugl'),
('10110',true,'w','anpra','Anthus pratensis','Wiesenpieper','Meadow Pipit','Engpiber'),
('02630',false,'ww','cipyg','Circus pygargus','Wiesenweihe','Montagu’s Harrier','Hedehøg'),
('13140',false,'wg','rereg','Regulus regulus','Wintergoldhähnchen','Goldcrest','Fuglekonge'),
('00462',false,'yss','pupuy','Puffinus puffinus yelkouan','Yelkouan-Schwarzschnabel-Sturmtaucher','Levantine Shearwater',''),
('10660',false,'z','trtro','Troglodytes troglodytes','Zaunkönig','Winter Wren','Gærdesmutte'),
('16649',false,'zu','carsp','Carduelis indet.','Zeisig unbestimmt','Goldfinch sp.','Carduelis sp'),
('07780',false,'zim','caeur','Caprimulgus europaeus','Ziegenmelker','Nightjar','Natravn'),
('13110',false,'zi','phcol','Phylloscopus collybita','Zilpzalp','Chiffchaff','Gransanger'),
('01558',false,'zss','cycoc','Cygnus columbianus/cygnus','Zwerg-/Singschwan','Bewick’s Swan/Whooper Swan','Pibesvane/Sangsvane'),
('01600',false,'zg','anery','Anser erythropus','Zwerggans','Lesser White-fronted Goose','Dværggås'),
('05780',true,'zm','lamin','Larus minutus','Zwergmöwe','Little Gull','Dværgmåge'),
('02200',false,'zsä','mealb','Mergus albellus','Zwergsäger','Smew (merganser)','Lille Skallesluger'),
('13430',false,'zws','fipar','Ficedula parva','Zwergschnäpper','Red-breasted Flycatcher','Lille fluesnapper'),
('05180',false,'ze','lymin','Lymnocryptes minimus','Zwergschnepfe','Jack Snipe','Enkeltbekkasin'),
('01532',false,'zw','cycol','Cygnus columbianus bewickii','Zwergschwan (Unterart bewickii)','Bewick’s Swan','Pibesvane (bewickii)'),
('06240',false,'zs','stalb','Sterna albifrons','Zwergseeschwalbe','Little Tern','Dværgterne'),
('05010',false,'zst','camin','Calidris minuta','Zwergstrandläufer','Little Stint','Dværgryle'),
('04110',false,'zsu','popus','Porzana pusilla','Zwergsumpfhuhn','Baillon’s Crake','Dværgrørvagtel'),
('00070',false,'zt','taruf','Tachybaptus ruficollis','Zwergtaucher','Little Grebe','Lille Lappedykker');
